### ISSUE TITLE
Missing release tags

### ISSUE THREAD

**Issue by yochananmarqos** [linuxmint/timeshift#1]
Manjaro and AUR packager here. The package version is based on the last release tag in teejee2008's repo, but the linuxmint repo has none. Could you import the releases / tags from the teejee2008 repo?

**Comment by clefebvre** [comment]
Thanks @yochananmarqos 

Tags were pushed.

**Comment by MartinX3** [comment]
I don't understand why you actively avoided to fork the upstream repo.
At least you didn't overwrite the previous commits author with your own useraccount....

**Comment by yochananmarqos** [comment]
teejee2008 just released [22.06.1](https://github.com/teejee2008/timeshift/releases/tag/v22.06.1) with the changes that are already here, can it be imported as well?
