### ISSUE TITLE
Size shared and unshared BTRFS snapshots missing in GUI

### ISSUE THREAD

**Issue by bkmo** [linuxmint/timeshift#10]
Size shared and unshared BTRFS snapshots missing in GUI.  Used to be there now it is absent. I'm curious why. It was very useful.
v22.06.1  Arch Linux

**Comment by Fantu** [comment]
was removed in https://github.com/linuxmint/timeshift/commit/c0737b15b2afb62f47f8d5b7f5a5c2afce8bf638
