### ISSUE TITLE
Fails to build in parallel

### ISSUE THREAD

**Issue by Schievel1** [linuxmint/timeshift#101]
**Describe the bug**
When I try to build timeshift with `-j4` I get many errors like 
`cc1: fatal error: /var/tmp/portage/app-backup/timeshift-22.06.5/work/timeshift-22.06.5/src/Utility/AppLock.vala.c: No such file or directory
compilation terminated.`

I watched the directory `src/Utility/` during compilation and those files are indeed created but later deleted again. 
It works with `-j1`.

**System:**
 - Gentoo Linux
 - Timeshift 22.11.1 but also have the same bug with 22.06.5 and 21.09.1

**Comment by yegorich** [comment]
It can be fixed with, for example, meson build system. See #173
