### ISSUE TITLE
qgroup errors in log but snapshots are created

### ISSUE THREAD

**Issue by jfabernathy** [linuxmint/timeshift#109]
To simplify the debugging of this I rebuilt the laptop directly from the 21.1 .iso and left the BTRFS alone; only @home and @. No additional grub-btrfs or timeshift-autosnap-apt. I ran timeshift from the gui and configured it; Daily and hourly, included @home.  There was not option for qgroups.  I did the first snapshot and the error is still in the log.

```
[09:03:14] btrfs qgroup show --raw '/run/timeshift/32350/backup'
[09:03:14] btrfs qgroup show '/run/timeshift/32350/backup'
[09:03:14] E: ERROR: can't list qgroups: quotas not enabled

[09:03:14] E: btrfs returned an error: 256
[09:03:14] E: Failed to query subvolume quota
[09:03:14] Query completed
```
```
jim@jim-XPS-15-9500:~$ cat /etc/timeshift/timeshift.json
{
  "backup_device_uuid" : "e2d310fa-825b-4228-a026-211244bf10c0",
  "parent_device_uuid" : "",
  "do_first_run" : "false",
  "btrfs_mode" : "true",
  "include_btrfs_home_for_backup" : "true",
  "include_btrfs_home_for_restore" : "false",
  "stop_cron_emails" : "true",
  "schedule_monthly" : "false",
  "schedule_weekly" : "false",
  "schedule_daily" : "true",
  "schedule_hourly" : "true",
  "schedule_boot" : "false",
  "count_monthly" : "2",
  "count_weekly" : "3",
  "count_daily" : "5",
  "count_hourly" : "6",
  "count_boot" : "5",
  "snapshot_size" : "0",
  "snapshot_count" : "0",
  "date_format" : "%Y-%m-%d %H:%M:%S",
  "exclude" : [],
  "exclude-apps" : []

```

**Comment by jfabernathy** [comment]
Also see discussion at 
https://forums.linuxmint.com/viewtopic.php?f=47&t=387641

**Comment by mtwebster** [comment]
This is fixed in https://github.com/linuxmint/timeshift/commit/02240c189895a93aa8b3f1ed473968cf74040564 but hasn't made it to a release yet.

This error can be ignored - the only way we can currently check if qgroups are enabled is by assuming they are and then catching the exit code. (We're open to better solutions to this...)
