### ISSUE TITLE
Configuration via Terminal

### ISSUE THREAD

**Issue by DonFruendo** [linuxmint/timeshift#11]
I was trying to configure Timeshift in my OS install script. Is there any option to do so without clicking in the GUI? I want to set the Weekly and Daily backups for example.

Newly installed today via `sudo apt install timeshift` on Pop!_OS 20.04

**Comment by xenopeek** [comment]
The Timeshift CLI doesn't let you configure scheduling but Timeshift stores scheduling and other settings in the file `/etc/timeshift/timeshift.json`. You can modify that file with other commands (e.g., with `sed` to change values) or copy a file there with pre-configured settings. The "schedule_monthly" and "schedule_weekly" variables can be set to "true" or "false" to enable or disable a snapshot being taken at that interval. The "count_monthly" and "count_weekly" variables set how many previous snapshots to keep of each.
