### ISSUE TITLE
Snapshots - don't offer BTRFS if the OS is not installed on a BTRFS

### ISSUE THREAD

**Issue by dandv** [linuxmint/timeshift#110]
Sorry for filing in this repo - not sure what the appropriate one is. I found the System Snapshots via the Welcome screen, and was confused by the initial choice - RSYNC vs. BTRFS.

![image](https://user-images.githubusercontent.com/33569/104899564-166c8100-591f-11eb-8838-a2387c605ab5.png)

BTRFS sounds badass, but my Mint installation uses `ext4`. Would it be possible to not confuse the user with an option that is not available to them?

**Comment by kj7rrv** [comment]
Hello! I think https://github.com/linuxmint/timeshift/issues/ would be the appropriate place for this issue.

**Comment by mtwebster** [comment]
This has been fixed since 22.06.4:

https://github.com/linuxmint/timeshift/commit/96f9f8134a84f2254a3f01fe17db07de9ee02a33
