### ISSUE TITLE
What do you think of this idea?

### ISSUE THREAD

**Issue by ghost** [linuxmint/timeshift#118]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

A recurring problem when recovering files and folders is storage space. Initially, I'm thinking of using things like remote-storage, IPFS, Hypercore, Git, Bittorrent to ensure that files are fully recovered in timeshift.

*What do you think of this idea?*

**Comment by rizajur** [comment]
> What do you think of this idea?

not smart to trust providers with your data, storage is cheap.
but something like samba / dav  over a network storage drive would be a very specific use case most people wont use.

This looks interesting - also special use case but with more users
https://github.com/linuxmint/timeshift/issues/139

or adding exclude paths etc over cli tools etc would be a need feature.
