### ISSUE TITLE
No snapshot listed on Ubuntu 22.04

### ISSUE THREAD

**Issue by antonio-petricca** [linuxmint/timeshift#171]
**Describe the bug**

After doing a (manual) backup it does not show up in the snapshots lists dialog.

**System:**
 - Linux Distribution Name and Version: Ubuntu 22.04
 - Desktop GNOME
 - Application Version 21.09.1

**Comment by fahmifan** [comment]
I'm experiencing this issue too, but when checking the target partition, there is the timeshift and the manual snapshot folder

**Comment by antonio-petricca** [comment]
I solved it by installing the latest release as described at https://ubuntuhandbook.org/index.php/2022/12/timeshift-ubuntu2204-backup-system/amp/ .
