### ISSUE TITLE
BTRFS and Docker

### ISSUE THREAD

**Issue by zabihexes** [linuxmint/timeshift#174]
**Describe the bug**
Timeshift breaks docker after restoring on BTRFS systems.

**To Reproduce**
1. Setup BTRFS system with timeshift
2. Setup docker
3. Restore any snapshot
4. Try to use docker

**Expected behavior**
Docker continues working fine

**Screenshots**

**System:**
 - Linux Distribution Name and Version: last seen on Fedora
 - Desktop KDE
 - Application Version [e.g. v18.8]

**Comment by Mart-Bogdan** [comment]
Hello, @Yaikava, why did you close it?

It actually don't work)

Basically it doesn't move any existing subvolumes that was present on filesystem after restore, and they remain on "old root".

I believe this also affects any user created sub-volumes, not docker ones.

**Comment by zabihexes** [comment]
> Hello, @Yaikava, why did you close it?
> 
> It actually don't work)
> 
> Basically it doesn't move any existing subvolumes that was present on filesystem after restore, and they remain on "old root".
> 
> I believe this also affects any user created sub-volumes, not docker ones.

Do not really remember honestly. Might have fixed it somehow. Was a long time ago.

Right now I just use podman and snapper which seems to work fine.

**Comment by Mart-Bogdan** [comment]
It definitely don't work with docker Out of a box.

I guess it can work if directory of docker subvomes is subvolume mount by fstab.

I guess Podman works because it stores containers inside $HOME and TimeShift don't restore home by default.



I have just added this to `/etc/fstab`

```
UUID=2e943f95-2258-42c4-93cb-1cef939d524e   /var/lib/docker/btrfs  btrfs subvol=/@docker,discard=async,ssd  0 0
```

Would test if it work after snapshot restore. But at least docker work with this config.

**Comment by Mart-Bogdan** [comment]
It survived one restoration from snapshot. Would observe further.

**Comment by zabihexes** [comment]
> I guess Podman works because it stores containers inside $HOME and TimeShift don't restore home by default.

yup
