### ISSUE TITLE
Please add the Timeshift app to Flatpak to make it available up-to-date to all to the latest version

### ISSUE THREAD

**Issue by NicolaeFericitu** [linuxmint/timeshift#185]
Please add the Timeshift app to Flatpak to make it available up-to-date to all to the latest version. In Linux Debian it often takes a very long time until a new update is released although it was released by the app developer a long time ago and is stable.

Not all Linux users know how to install applications from source code, so please help us. I consider Timeshift a wonderful and essential application for Linux systems. Thank you for taking on this project and keeping it alive.

Flatpak—the future of application distribution
The future of apps on Linux
https://www.flatpak.org/

Thank you!

**Comment by xenopeek** [comment]
Duplicate of #129
