### ISSUE TITLE
Non-standard man page

### ISSUE THREAD

**Issue by rebelxt** [linuxmint/timeshift#195]
**Describe the bug**
The man page for **timeshift** is written in a non-standard format.

**To Reproduce**
 Issue the command: **man timeshift**

**Sugested fix**
Generate a standard format man page using the **help2man** command.

**System:**
Any version of Linux Mint

**Comment by yegorich** [comment]
Already fixed in https://github.com/linuxmint/timeshift/pull/178. The issue can be closed.
