### ISSUE TITLE
Clarification for Fork

### ISSUE THREAD

**Issue by Termuellinator** [linuxmint/timeshift#2]
Hi there,
i assume timeshift was adopted into the Mint project? I noticed from the updated AUR-Package and am a bit confused because there is no note on the teejee2008 repo and it doesn't seem abandoned with the last commits from april?

I doubt i'm the only one, so i think a note/explanation in the readme.md might be a good idea imho. And if teejee2008 is in on the whole thing, best add a note to the old repo, too.

Thanks! :)

**Comment by MartinX3** [comment]
They actively avoided the GitHub fork feature to prevent people to easily click on the upstream project window of the repository web page.

Also the original author updates the application.

I miss transparency...

**Comment by yochananmarqos** [comment]
The teejee2008 README was [just updated](https://github.com/teejee2008/timeshift/commit/9d614d5e2e20cb4486b4f4becf7f60c5cd0dea1a), FYI.

**Comment by clefebvre** [comment]
> They actively avoided the GitHub fork feature to prevent people to easily click on the upstream project window of the repository web page.

This was done on purpose when it became a real fork (i.e. not just a github work copy).

Tony updated his README. I also got an email from him about the commits he added. I'll rebase or cherry pick to get them added here.
