### ISSUE TITLE
Exclude pattern not working.

### ISSUE THREAD

**Issue by harley-codes** [linuxmint/timeshift#215]
**Describe the bug**
The exclusion does not seem to be working for me. My steam downloads are still being bundled in backups.

**To Reproduce**
1. Setup as per screenshot, where exclude is something in your home dir that you want excluded.
2. Run manual backup
3. Browse Backup 

**Expected behavior**
Excluded folder should not be present in backup.

**Screenshots**
![image](https://github.com/linuxmint/timeshift/assets/13950165/f1c17285-12f0-444f-9447-36f852ef34c9)
![image](https://github.com/linuxmint/timeshift/assets/13950165/f0142068-61c7-4e45-9fd2-2c511001584b)
![image](https://github.com/linuxmint/timeshift/assets/13950165/eecf5c86-2ac6-47ce-a0c3-f282cabe94a4)

**System:**
 - Linux Distribution Name and Version: Zorin Pro 16.2
 - Application Version:  v20.03

**Comment by ykarrde** [comment]
Have you seen the "Drag-drop to reorder" hint, near top right?
I would assume you maybe have to drag your exclusion to the top or at least higher than the inclusion of your complete home directory to give the exclusion a higher priority.

Just a guess, not tried myself, maybe you have already tried and just forgotten to mention?

Disclaimer: I'm not affiliated with the Timeshift development in any way or form.

**Comment by harley-codes** [comment]
Hey @ykarrde, I believe I did try re-ordering. What I think was happening is I added the rule after an initial scan where files from that space were included. Somehow I think this affected the exclusion rule and continued to include future files. So if someone stumbled across this. 1) Rule must be at top. 2) Do before fist backup, otherwise, clear past backups??
