### ISSUE TITLE
TimeShift backup resulted not usable snapshot

### ISSUE THREAD

**Issue by laszloatoth** [linuxmint/timeshift#229]
**Describe the bug**

I used to used for several years TimeShift without any problem but now the latest version app is not able to recognize the snapshot that created by itself, by the same app instance.
When will it be appeared a usable TimeShift version?

**To Reproduce**
First I used the GUI to create a snapshot on my Ubuntu 22.04 op. system on an external storage. (on external WD MyPassport optical storage connected via USB cable)

Later I wanted to see the snapshot in the TimeShift GUI, but cannot be seen, not visible.

Finally I used the command prompt version to realize what is the situation:

laci@Sanyika:~$ sudo timeshift --list-devices

/dev/sdd1 is mounted at: /run/timeshift/backup, options: rw,relatime,errors=remount-ro

Devices with Linux file systems:

Num     Device              Size  Type  Label       
------------------------------------------------------------------------------
0    >  /dev/sda2        81.9 GB  ext4              
1    >  /dev/sda4       651.7 GB  ext4              
2    >  /dev/sdb1       500.1 GB  ext4              
3    >  /dev/sdd1         2.0 TB  ext4  MyPassport  
4    >  /dev/nvme0n1p2   81.9 GB  ext4              
5    >  /dev/nvme0n1p4  901.8 GB  ext4              

laci@Sanyika:~$ sudo timeshift --list

/dev/sdd1 is mounted at: /run/timeshift/backup, options: rw,relatime,errors=remount-ro

Device : /dev/sdd1
UUID   : f3f315cc-89b3-4a8e-acf8-4ae9e3a686b4
Path   : /run/timeshift/backup
Mode   : RSYNC
Status : No snapshots on this device
First snapshot requires: 50 B

No snapshots found

This sentence is that I never wanted to see.
**Expected behavior**
Instead of the described behavior above I expect to create a usable snapshot that I can recover

**Screenshots**

**System:**
 Linux Sanyika 6.2.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
![image](https://github.com/linuxmint/timeshift/assets/60490572/436b0bd6-d3be-4afa-b48e-fda0fa01703c)

![image](https://github.com/linuxmint/timeshift/assets/60490572/c16785c8-95ea-4bd3-9877-4fb0f755d0a7)

**Comment by leigh123linux** [comment]
Don't double post!  https://github.com/linuxmint/timeshift/issues/218
