### ISSUE TITLE
Check for space before taking snapshot.

### ISSUE THREAD

**Issue by Andy2051** [linuxmint/timeshift#23]
We get too many posts on the LM forum from new users complaining "I can't boot" and one of the most common reasons is that timeshift has filled up a / partition that is too small. 

Surely it can't be too difficult to incorporate some space checking in timeshift, either:

- When it first enabled, checking the free space on the destination partition and warning or inviting the user to select a different partition if insufficient space available.

- Checking free space each time timeshift takes a snapshot.

**Comment by mtwebster** [comment]
This has been addressed (for rsync):
https://github.com/linuxmint/timeshift/commit/22b0e16a265a0debf2227390520ada1954e3f093

**Comment by Andy2051** [comment]
Ask and you shall receive!

Thanks.
