### ISSUE TITLE
Support for multiple backup targets.

### ISSUE THREAD

**Issue by Supermagnum** [linuxmint/timeshift#230]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
In my instance I have both a drive in my computer, and a shared drive on a remote server. It whould be so nice if I could backup to the drive in my computer and the network drive simultaneously.

**Comment by Supermagnum** [comment]
Any progress on this?

**Comment by zahlman** [comment]
Timeshift is for restoration, not backup. It sounds like what you're really trying to accomplish is to have a backup of the restore data.

I would just set up Timeshift to back up to the local drive, then periodically rsync to the network drive. Then if the local drive data gets corrupted somehow, you can rsync back first before using it for system restoration.

If you really want to back up user data, other tools like BackInTime make more sense. Or you can work with rsync directly.
