### ISSUE TITLE
TURN OFF Gear icon on taskbar 

### ISSUE THREAD

**Issue by madmadman** [linuxmint/timeshift#254]
Every hour, on the hour, Timeshift does its hourly maintenance task and I spot an icon on my taskbar with two little gears. I'm sick and tired of catching it out of the corner of my eye. How do I prevent the gear icon from appearing on my taskbar? I want to disable it.
![Timeshift Gears](https://github.com/linuxmint/timeshift/assets/11094850/9e7704ec-45f2-4fae-be4e-e9d3f942520d)

Timeshift v 22.11.2
Linux Mint 21.1 Cinnamon

**Comment by soulstenance** [comment]
I believe this is a Mint exclusive feature. That said, why do you not want this? This was added, I believe, in Mint 21 so you can know when an automated task is running and you can avoid, for example, shutting down during an automated task. I believe this is a Mint icon, not a Timeshift icon but I could be wrong on that. It's a good feature but it would be nice to perhaps have some config options on right click.

**Comment by madmadman** [comment]
I just don't want to see it anymore. It annoys the heck out of me.

**Comment by mtwebster** [comment]
switch off Menu -> Startup Applications -> System Reports

**Comment by madmadman** [comment]
> switch off Menu -> Startup Applications -> System Reports

This did it! The gears aren't appearing every hour anymore. Thank you! So long as Timeshift is still making backups, I'm happy. Thank you!

**Comment by soulstenance** [comment]
> I just don't want to see it anymore. It annoys the heck out of me.

Fair enough. I guess I can see that coming up every hour getting annoying. Thank goodness Linux (and opensource in general) gives us choice!

**Comment by soulstenance** [comment]
> switch off Menu -> Startup Applications -> System Reports

It's worth noting that this will also turn off automatically checking for system issues, so you'll have to manually run System Reports from the main menu and refresh it if you happen to run into problems. Not a big deal though - the trade off is probably worth it if you want rid of that icon.
