### ISSUE TITLE
Aur package out of date 

### ISSUE THREAD

**Issue by ghost** [linuxmint/timeshift#3]
When I ran "yay" in the terminal I got this - https://paste.rs/ij7
" -> Flagged Out Of Date AUR Packages:  timeshift" 
And if u see here - https://aur.archlinux.org/packages/timeshift 
It is flagged out of date 
"Flagged out-of-date (2022-05-28) "
So is it ok for me to use timeshift which is flagged out of date ?

**Comment by xenopeek** [comment]
See https://aur.archlinux.org/packages/timeshift#comment-866988
