### ISSUE TITLE
[Question] How to offline restore master snapshot of btrfs system?

### ISSUE THREAD

**Issue by m1karii** [linuxmint/timeshift#315]
I use EndeavourOS with btrfs backups and my PC crashed mid full upgrade resulting in it not being bootable. I was able to select snapshot I manually created prior in grub and boot into it. I tried restoring it and here comes the problem: timeshift seems to restore selected snapshot over currently running one not over the master one resulting in it doing practically nothing (overwriting itself) and now I have to select to boot to this specific snapshot in grub every time i turn on PC. How do I restore selected snapshot over the master one? or overwrite the master one with the current one?

**Comment by teejee2008** [comment]
Boot from a live USB system and restore it.

**Comment by m1karii** [comment]
can you please elaborate on that @teejee2008 ?
I ve tried chrooting into the system however the timeshift on the master snapshot wont even start due to the following error: 
```
timeshift: symbol lookup error: /usr/lib/libvte-2.91.so.0: undefined symbol: ucnv_toUnicode_74
```
the README mentions "offline restore" however I seem to be unable to find more details about it

**Comment by teejee2008** [comment]
Write the Linux Mint ISO to a USB drive and boot from it. Run Timeshift from the live system. Select the system drive and the snapshot to restore and restore it.

**Comment by m1karii** [comment]
worked. thanks.
In case there happens to be someone with the same issue decade from now: you do NOT want to restore /home subvolume.
