### ISSUE TITLE
[ FR /Question ] Restore across OS upgrades

### ISSUE THREAD

**Issue by jayb-g** [linuxmint/timeshift#355]
If I understand it correctly, timeshift lets you restore to a **full** snapshot of your system at a previous date, without cherry-picking specific stuff to restore/re-install to a newly installed(and possibly upgraded) OS. Such as desktop environment(such as KDE), system configurations, extensions etc. And so you lose everything after the particular snapshot. If you restore, you restore fully. Meaning If I upgrade to 24.04 from 22.04 and use timeshift, I basically go back to 22.04 which I don't want. I want the latest OS with my preferred configurations/tools on top it. (I'm excluding the custom files/folders backup in this context) 

**Describe the solution you'd like**
Not sure if/how it can be implemented.

**Describe alternatives you've considered**
Custom scripts to automate re-setup of the system.

**Additional context**
Maybe timeshift is not the right tool for what I want?

**Comment by teejee2008** [comment]
Timeshift will restore the full snapshot and change the new system back to the old one. Use [Aptik](https://store.teejeetech.com/product/aptik/) to reapply your settings and software on a new system.

**Comment by jayb-g** [comment]
@teejee2008 

> Use Aptik to reapply your settings and software on a new system.

Looks good. Is it not foss anymore?
