### ISSUE TITLE
Please add a "confirmation" window for dangerous actions like "delete"

### ISSUE THREAD

**Issue by amhoba** [linuxmint/timeshift#369]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When I click the "Delete" or any other dangerous action throughout the software it should show me a prompt window asking for confirmation instead of just doing it!

**Describe alternatives you've considered**
None

**Additional context**
...

**Comment by ygerlach** [comment]
Sounds like a duplicate to #361

**Comment by amhoba** [comment]
Thanks @ygerlach , overall I gave up on the idea of using timeshift because it can not take snapshot of the whole system (snap packages etc.)
