### ISSUE TITLE
Timeshift will delete snapshot without confirmation dialog

### ISSUE THREAD

**Issue by Tenebris-Umbra** [linuxmint/timeshift#38]
If you look at the first three commands on the gui/menu bar of timeshift, in this order, you have Create, Restore and Delete. If you pick a snapshot and go to restore, but for some reason hit delete, it deletes the snapshot without confirmation and your snapshot is gone, this in my humble opinion is a bug, before deleting any snapshot, it should ask; Are you really sure you want to preform this operation. This is for data safety sake of snapshot, which may be needed.

**Comment by jjroysdon** [comment]
#18

**Comment by Tenebris-Umbra** [comment]
fixed in Mint 22
