### ISSUE TITLE
Show warning message if there is no space left on device

### ISSUE THREAD

**Issue by dbadura** [linuxmint/timeshift#41]
**Is your feature request related to a problem? Please describe.**
Recently I found out that I run out of the space on my disk and had one year old snapshots.

**Describe the solution you'd like**
I would like to get notification when `No space left on device` error occurs.

**Additional context**
I am using Ubuntu 18.04 with Gnome and Timeshift v19.08
https://github.com/teejee2008/timeshift/issues/719

**Comment by leigh123linux** [comment]
This commit (fixed in v22.06.3) looks like it addresses the issue.

https://github.com/linuxmint/timeshift/commit/22b0e16a265a0debf2227390520ada1954e3f093
