### ISSUE TITLE
Installation in Ubuntu Jammy

### ISSUE THREAD

**Issue by LorenzoBettini** [linuxmint/timeshift#60]
Hi

I'm a bit confused about the installation on Ubuntu Jammy. In the README you say

> Debian, Ubuntu, Linux Mint, Elementary OS, etc.

> Install Timeshift from the repositories:

> sudo apt-get update
> sudo apt-get install timeshift

That works, but I get an old version of Timeshift (v21.09.1). Is there a specific PPA to get the latest version? The old Timeshift Github, https://github.com/teejee2008/timeshift, mentions a PPA, but I seem to understand that is the old version of Timeshift anyway, isn't it?

In the README you also mention an "installer" but again I don't understand what it is.

Thanks

**Comment by leigh123linux** [comment]
See https://github.com/linuxmint/timeshift/issues/21#issuecomment-1203862781

**Comment by LorenzoBettini** [comment]
Thanks, I hadn't seen that.

But what about the installer mentioned in the readme?

**Comment by leigh123linux** [comment]
> Thanks, I hadn't seen that.
> 
> But what about the installer mentioned in the readme?

The instructions in the Readme look correct, file your issue against the ubuntu package and ask them to provide a newer package.

 https://packages.ubuntu.com/source/jammy/timeshift

Or do your own build, ppa or whatever.

**Comment by LorenzoBettini** [comment]
Thanks again, but I still don't understand what you mean by the installer. By installer do you mean building from sources?

**Comment by leigh123linux** [comment]
I think this PR clarifies the readme.

https://github.com/linuxmint/timeshift/pull/45/files

**Comment by LorenzoBettini** [comment]
@leigh123linux, the PR shows how to build it from the source, which is really helpful.
But that is not an "installer." Do you mean "building from source" when you mention the "installer" in the README?
