### ISSUE TITLE
Critical error when copying

### ISSUE THREAD

**Issue by LibertyGM** [linuxmint/timeshift#66]
**Describe the bug**
There are bugs in the operation of the program. First, it stopped showing the remaining time, just three question marks. Now the GUI crashes when copying and deleting, but the process itself on the system continues.

**To Reproduce**
1. I open the program.
2. I start copying rsync.
3. After a while, the program window closes abruptly.

It also says "???" instead of the remaining time.

**Expected behavior**
I expected the copying to be successful.

Log file:
https://pastebin.com/FtQ4aqqE
[Timeshift log.txt](https://github.com/teejee2008/timeshift/files/9639037/Timeshift.log.txt)

**System:**
 - Arch Linux
 - KDE Plasma
 - Application Version 22.06.5

**Comment by cimarronline** [comment]
This issue seems to be related to the update to glib2 2.74.0. Downgrading glib2 restores proper functionality. Also, timeshift cli seems unaffected.

**Comment by LibertyGM** [comment]
> This issue seems to be related to the update to glib2 2.74.0. Downgrading glib2 restores proper functionality. Also, timeshift cli seems unaffected.

Yes, cli Timeshift fortunately still works, but the remaining time there is also not shown. I wish they would fix the GUI too. I don't want to roll something back because other components might stop working.

If I understand you correctly - no one is going to fix the problem?

**Comment by cimarronline** [comment]
I think it will get fixed; I'm just providing more information. Timeshift is an important application for Mint. But I'm guessing it might be a while before Mint moves to glib2 2.74, so it doesn't affect their users right now.

**Comment by attishno1** [comment]
A recent update seems to have fixed everything. Does anyone know which update may have fixed it. It is working fine for me today!

**Comment by LibertyGM** [comment]
> A recent update seems to have fixed everything. Does anyone know which update may have fixed it. It is working fine for me today!

What system do you have and what version of the program do you have and where did you install it from?

**Comment by attishno1** [comment]
I installed it from the AUR. Version is 22.06.5. I am using EndeavorOS

**Comment by LibertyGM** [comment]
Strange, I have the same version, it as far as I know back in the spring. Yesterday nothing worked, today has not tried yet. Do you get the time to the end of the backup when you create a backup?

**Comment by attishno1** [comment]
I am using the CLI. Yes, it works. No idea why it has started working again. Glib did not get an update. It just all of a sudden started working.

It is even now displaying Snapshots on both CLI and GUI. It didn't before.

**Comment by mtwebster** [comment]
It's this bug maybe: https://gitlab.gnome.org/GNOME/glib/-/commit/ea3f17d598d550345e94e4571130e429443e91cb

ref: https://bugs.archlinux.org/task/75980

Looks like the fix is in 2.74.0-2 in arch

**Comment by LibertyGM** [comment]
> It's this bug maybe: https://gitlab.gnome.org/GNOME/glib/-/commit/ea3f17d598d550345e94e4571130e429443e91cb
> 
> ref: https://bugs.archlinux.org/task/75980
> 
> Looks like the fix is in 2.74.0-2 in arch

I'm not very good at all of this. Can I put it in simpler words? How do I understand the error was corrected?

**Comment by mtwebster** [comment]
On arch maybe:
```
pacman -Qi glib2
```
to see what version you're on.

disclaimer: I don't use Arch

**Comment by attishno1** [comment]
> > It's this bug maybe: https://gitlab.gnome.org/GNOME/glib/-/commit/ea3f17d598d550345e94e4571130e429443e91cb
> > ref: https://bugs.archlinux.org/task/75980
> > Looks like the fix is in 2.74.0-2 in arch
> 
> I'm not very good at all of this. Can I put it in simpler words? How do I understand the error was corrected?

According to the message, Arch Linux has an update for a package called glib2. glib2 update probably fixed the time shift issue.

**Comment by attishno1** [comment]
It is strange. I have glibc2 2.74.0-1 and the problem magically disappeared. It never updated, I was wrong!

**Comment by LibertyGM** [comment]
I had the problem as it was, and still is. Unfortunately, it didn't work all of a sudden.

**Comment by attishno1** [comment]
Yes. I even have posted on Arch Linux Forums about this issue. So far, I have not discovered why it is working for me.

**Comment by wenjun115** [comment]
@imLEGR @attishno1 I used "sudo downgrade glib2 " to change to the 2.72.3 version it started working

**Comment by Seele0oO** [comment]
```
pacman -Q glib2                                                                                
glib2 2.74.0-2
``` 
not fix,
I  downgrade to 2.72.3 and reboot.
now it works ok.

Upgrade:
downgrade glib2 may cause chromium error.fcitx5 may not work as usual.
will timeshift or glib2 will fix it quickly ?
```
Gtk-Message: 16:57:19.665: Failed to load module "appmenu-gtk-module"

(chromium:81134): Gtk-WARNING **: 16:57:19.889: GModule (/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so) initialization check failed: GLib version too old (micro mismatch)

(chromium:81134): Gtk-WARNING **: 16:57:19.889: Loading IM context type 'fcitx' failed

```

**Comment by attishno1** [comment]
Timeshift CLI works right now. I do not know when the Mint team will fix this.

**Comment by guiNovais** [comment]
I am facing the same trouble, so I downgraded glib2 to v2.72.3-3 and have add it to IgnorePkg. I know it is a way to mitigate, but is the only way i found to keep my backups with timeshift...

**Comment by attishno1** [comment]
> I am facing the same trouble, so I downgraded glib2 to v2.72.3-3 and have add it to IgnorePkg. I know it is a way to mitigate, but is the only way i found to keep my backups with timeshift...

The CLI is not working either for you?

**Comment by guiNovais** [comment]
> > I am facing the same trouble, so I downgraded glib2 to v2.72.3-3 and have add it to IgnorePkg. I know it is a way to mitigate, but is the only way i found to keep my backups with timeshift...
> 
> The CLI is not working either for you?

The CLI does work, but only manual backups and restores. The ones schedule daily, weekly, etc, don't (and I checked the cronie.service)

**Comment by attishno1** [comment]
> > > I am facing the same trouble, so I downgraded glib2 to v2.72.3-3 and have add it to IgnorePkg. I know it is a way to mitigate, but is the only way i found to keep my backups with timeshift...
> > 
> > 
> > The CLI is not working either for you?
> 
> The CLI does work, but only manual backups and restores. The ones schedule daily, weekly, etc, don't (and I checked the cronie.service)

I am quite surprised that a fix for this hasn't arrived yet.

**Comment by mtwebster** [comment]
Assuming it's the same bug, this should be fixed in the latest timeshift version 

https://github.com/linuxmint/timeshift/issues/91#issuecomment-1325967427

**Comment by topas-rec** [comment]
Tested a create and delete snapshot cycle  in the GUI on arch in version 22.11.1-1. Worked without problem.

**Comment by guiNovais** [comment]
> Tested a create and delete snapshot cycle in the GUI on arch in version 22.11.1-1. Worked without problem.

I also tested here with 2.74.2-2 and it did work
