### ISSUE TITLE
Documentation of tags

### ISSUE THREAD

**Issue by SilentWarrior83** [linuxmint/timeshift#77]
Here's a (hopefully) low-hanging fruit for you all: I've been looking for an explanation of the backup tags (tab Tags in main view), but I never managed to find any. I mean the O M D B, and whatever else. I imagine that most signify the periodicity (**M**onthly, **D**aily), but there are others I want to know more about.
An extra section in either the online documentation or the man pages is all I want.

**Comment by mtwebster** [comment]
If you hover over the letters it explains the different types in a tooltip.
