### ISSUE TITLE
Timeshift an rsync 3.2.4

### ISSUE THREAD

**Issue by DerKlausner** [linuxmint/timeshift#8]
Timeshift 21.09.1-1
rsync  3.2.4
Timeshift are not running with rsync 3.2.4
The snapshot is starting, but after the snapshot i can not see the in the gui.
If i look in the timeshift directory is no link in the order ondemant, weekly, and so on.
But i have a the snapshot in directory timeshift/snapshot
With an older Version from rsync is timeshift running without Problems.

**Comment by xenopeek** [comment]
You need Timeshift 22.06 or newer with rsync 3.2.4. This is fixed by https://github.com/linuxmint/timeshift/commit/de55e7916d6002b516898fe22d0f83f44936fd64.
