### ISSUE TITLE
Timeshift does not create snapshots with latest RSync

### ISSUE THREAD

**Issue by MStarha** [linuxmint/timeshift#93]
**Describe the bug**
Timeshift in rsync mode does not create any scheduled snapshots. The program is active (if I try to open it at the correct time, it says that another one is already running), but no snaphots are created in the storage location, and no snapshots are visible in the Timeshift GUI. However, if I create a snapshot manually (on demand), the snapshot is still not visible in the Timeshift GUI, but it is in the correct snaphot location. What helped was to downgrade RSync from latest 3.2.7 to 3.2.3. Using Timeshift v21.09.1.

**To Reproduce**
1. Setup regular snapshots.
2. Wait for one to be created
3. Observe that no snapshot is visible in Timeshift GUI or in the storage location.

1. Create a snaphot manually (on demand)
2. Observe that no snapshot is visible in Timeshift GUI but is visible in the storage location.

**Expected behavior**
To actually create snapshots and not just pretend.

**Screenshots**

**System:**
 - Linux Distribution Name and Version: Fedora 36
 - Desktop: Cinnamon 5.2.7
 - Application Version: RSync 3.2.7, Timeshift v21.09.1

**Comment by leigh123linux** [comment]
You will need to get the fedora maintainer to update or patch. https://bugzilla.redhat.com/

 https://github.com/linuxmint/timeshift/commit/de55e7916d6002b516898fe22d0f83f44936fd64
